name: test_env
channels:
- defaults
- conda-forge
dependencies:
- dask-core >2.0
- dill
- h5py
- imageio
- ipyparallel
- matplotlib-base
- matplotlib-scalebar
- mrcz
- natsort
- numba
- numexpr
- numpy
- pint
- prettytable
- python
- python-dateutil
- pyyaml
- requests
- scikit-image
- scikit-learn
- scipy
- sparse
- sympy
- tifffile >=2019.07.26,!=2021.3.31
- toolz
- tqdm
- traits


