name: test_env
channels:
- conda-forge
dependencies:
- dask-core >=2021.3.1
- dill
- importlib-metadata
- h5py
- jinja2
- matplotlib-base >=3.1.3
- natsort
- numba >=0.52
- numexpr
- numpy >=1.20
- packaging
- pint >=0.10
- prettytable >=2.3
- python-dateutil >=2.5.0
- pyyaml
- requests
- rosettasciio-base
- scikit-image >=0.18
- scikit-learn >=1.0.1
- scipy >=1.6.0
- sympy >=1.6.0
- tqdm >=4.9.0
- traits >=4.5.0
