name: 'Nightly Merge'

on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  nightly-merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.3
      with:
        stable_branch: 'RELEASE_next_minor'
        development_branch: 'non_uniform_axes'
        allow_ff: true
        allow_forks: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
