name: Release
# This workflow builds the wheels "on tag".
# If run from the hyperspy/hyperspy repository, the wheels will be uploaded to pypi ;
# otherwise, the wheels will be available as a github artifact.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844

  build_wheels:
    name: Wheels on ${{ matrix.os }}/py${{ matrix.python-version }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: What OS and Python version
        run: |
          uname -a
          python --version
          which python

      - name: install build and twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build wheels
        run: |
          python -m build

      - name: Display content dist folder
        run: |
          ls dist/

      - name: Install and test distribution
        env:
          MPLBACKEND: agg
        run: |
          pip install --pre --find-links dist hyperspy[tests]==1.7.6
          pytest --pyargs hyperspy

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl

      - name: Publish wheels to PyPI
        if: github.repository_owner == 'hyperspy'
        env:
          # Github secret set in the hyperspy/hyperspy repository
          # Not available from fork or pull request
          # Secrets are not passed to workflows that are triggered by a pull request from a fork
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*.whl --verbose

  build_wheels_linux:
    name: Wheels on ubuntu-latest
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build source distribution
        run: |
          pip install build
          python -m build --sdist

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@ff8504699f7a33a08d3ff85b3c6d4e8f0e70462b
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311'
          build-requirements: 'cython'

      - name: Display content dist folder
        run: |
          ls dist/

      - name: Install and test distribution
        env:
          MPLBACKEND: agg
        run: |
          pip install --pre --find-links dist hyperspy[tests]==1.7.6
          pytest --pyargs hyperspy

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: |
            ./dist/*-manylinux*.whl
            ./sdist/*.tar.gz

      - name: Publish wheels to PyPI
        if: github.repository_owner == 'hyperspy'
        env:
          # Github secret set in the hyperspy/hyperspy repository
          # Not available from fork or pull request
          # Secrets are not passed to workflows that are triggered by a pull request from a fork
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*-manylinux*.whl --verbose 
          twine upload dist/*.tar.gz --verbose 

      # Don't use the pypa publish action for now as we need to filter the `linux` wheels
      # With hyperspy 2.0, it will be noarch and the release workflow will refactor
      # - name: Publish wheels to PyPI
      #   if: github.repository_owner == 'hyperspy'
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     # Github secret set in the hyperspy/hyperspy repository
      #     # Not available from fork or pull request
      #     # Secrets are not passed to workflows that are triggered by a pull request from a fork
      #     password: ${{ secrets.PYPI_API_TOKEN }}
